[versions]
agp = "8.13.2"
circleimageview = "3.1.0"
converterGson = "2.3.0"
firebaseBom = "34.8.0"
glide = "5.0.5"
googleGson = "2.13.2"
gsonVersion = "2.8.6"
javaWebsocket = "1.6.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
jwtdecode = "2.0.2"
material = "1.13.0"
activity = "1.12.1"
constraintlayout = "2.2.1"
mpandroidchart = "v3.1.0"
navigation-fragment = "2.9.6"
navigation-ui = "2.9.6"
legacySupportV4 = "1.0.0"
okhttpVersion = "4.11.0"
recyclerview = "1.3.0"
okhttp = "4.9.3"
osmdroidAndroid = "6.1.14"
gson = "2.10.1"
retrofitVersion = "2.3.0"
rxandroid = "2.1.1"
rxjava = "2.2.21"
secretsGradlePlugin = "2.0.1"
retrofit = "3.0.0"
stompprotocolandroid = "1.6.6"
lifecycleProcess = "2.10.0"


[libraries]
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
converter-gson-v230 = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson-v2132 = { module = "com.google.code.gson:gson", version.ref = "googleGson" }
gson-v286 = { module = "com.google.code.gson:gson", version.ref = "gsonVersion" }
java-websocket = { module = "org.java-websocket:Java-WebSocket", version.ref = "javaWebsocket" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
jwtdecode = { module = "com.auth0.android:jwtdecode", version.ref = "jwtdecode" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigation-fragment"}
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigation-ui"}
legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupportV4" }
okhttp-v4110 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttpVersion" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
osmdroid-android = { module = "org.osmdroid:osmdroid-android", version.ref = "osmdroidAndroid" }
osmdroid-geopackage = { module = "org.osmdroid:osmdroid-geopackage", version.ref = "osmdroidAndroid" }
osmdroid-wms = { module = "org.osmdroid:osmdroid-wms", version.ref = "osmdroidAndroid" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
retrofit-v230 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
rxandroid = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "rxandroid" }
rxjava = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava" }
secrets-gradle-plugin = { module = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin", version.ref = "secretsGradlePlugin" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
stompprotocolandroid = { module = "com.github.NaikSoftware:StompProtocolAndroid", version.ref = "stompprotocolandroid" }
lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycleProcess" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
